name: R-CMD-check

on:
  push:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.1'

      - name: Install dependencies
        run: |
          install.packages(c("httr", "jsonlite", "tibble", "dplyr", "tidyverse", "lubridate", "scales", "roxygen2", "testthat"))
          remotes::install_github("r-lib/covr")

      - name: Run tests
        run: Rscript -e 'devtools::test()'
