---
title: "Untitled"
author: "Jacob Rosen"
date: "2024-01-26"
output: html_document
---

```{r}
library(httr)
library(jsonlite)
library(ggplot2)
library(ggmap)
library(sp)
library(leaflet)
library(htmltools)

api_key <- 'fVnQw6kAGUfwkaLWnhgmNmW7S6SxVx4E27oJgDG9'

# metadata request
get_metadata <- function(type='natural', date = NULL){
  
  base_url <- paste("https://api.nasa.gov/EPIC/api/", type, sep = '')
  # Construct the URL
  url <- ifelse(is.null(date), base_url, paste0(base_url, "/date/", date))
  
  # Make the API request
  response <- GET(url, query = list(api_key = api_key))
  
  # Check for successful response
  if (http_type(response) == "application/json") {
    # Parse the JSON response
    data <- fromJSON(content(response, "text", encoding = "UTF-8"))
    return(data)
  } else {
    stop("Failed to retrieve data from the EPIC API.")
  }
    
}

```

```{r}
# get image url
get_image_urls <- function(type='natural', date = NULL){
  data <- get_metadata(type, date)
  year <- substr(data$date, 1, 4)
  month <- substr(data$date, 6, 7)
  day <- substr(data$date, 9, 10)
  image_urls <- paste('https://epic.gsfc.nasa.gov/archive', type, year, month, day, 'png', data$image, sep = '/')
  image_urls <- paste(image_urls, '.png', sep = '')
  image_urls
}
```

```{r}
data <- get_metadata()
```

```{r}
plot_centroid <- function(type='natural', date = NULL){
  data <- get_metadata(type, date)
  df <- data.frame(longitude = data$centroid_coordinates$lon, 
                 latitude = data$centroid_coordinates$lat,
                 name = data$image)
  
  leaflet(df) %>% addTiles() %>% addMarkers(~longitude, ~latitude, label = ~htmlEscape(name))
}
```

