name: r_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.1.1']

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("httr")'
          Rscript -e 'install.packages("jsonlite")'
          Rscript -e 'install.packages("tibble")'
          Rscript -e 'install.packages("ggplot2")'
          Rscript -e 'install.packages("dplyr")'
          Rscript -e 'install.packages("readr")'
          Rscript -e 'install.packages("tidyr")'
          Rscript -e 'install.packages("lubridate")'
          Rscript -e 'install.packages("scales")'
          Rscript -e 'install.packages("roxygen2")'
          Rscript -e 'install.packages("testthat")'
          Rscript -e 'install.packages("leaflet")'
          Rscript -e 'install.packages("htmltools")'
      - name: Run tests
        run: |
          Rscript -e 'testthat::test_file("test_file.R")'
