name: r_test

on:
  push:
    branches:
      - main

jobs:
  R-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.3.1'

      - name: Install dependencies
        run: |
          install.packages(c("httr", "jsonlite", "tibble", "dplyr", "tidyverse", "lubridate", "scales", "roxygen2", "testthat"))

      - name: Run tests
        run: Rscript -e 'testthat::test_file("test_file.R")'
